apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: simple-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hostname-deployment
  maxReplicas: 5
  minReplicas: 1
  targetCPUUtilizationPercentage: 50
